### ISSUE TITLE
AuthenticationTokenSchema after Login

### ISSUE THREAD

**Issue by Alainy** [omisego/ewallet#183]
# AuthenticationTokenSchema

In Swagger the example response for a successful login in the AdminAPI has the following AuthenticationTokenSchema:
```
object string
authentication_token string
user_id string
user UserSchema
account_id string
account AccountSchema
```

But when I do an actual login it also returns the key `master_admin bool`. Is there a reason for this or is it missing from the example?

# Your environment

Commit 169bf5c

**Comment by Alainy** [comment]
Also in the MintedTokenSchema it says `subunit_to_unit boolean` but I think this should be `subunit_to_unit integer`.

**Comment by unnawut** [comment]
`master_admin` is very recent (last week I think). Sorry for missing that from the schema.

Basically it's a boolean flag that tells whether the user holding that token is an admin on the master account or not. 

And the "master account" is the name we're using for the top-level account. Only one master account exists in a given ewallet system. Because it's the top-level account, we're also granting the admin on master account to manage system-wide settings such as create minted tokens, etc. _Note: we're still adding permissions to cover all actions._

**Comment by unnawut** [comment]
If you'd like to work on this please let us know. Otherwise I'll put this into our queue. Thanks again!

**Comment by Alainy** [comment]
Yea sure I'll pick it up
