### ISSUE TITLE
Allow multiple wallets balances to be retrieved from the local ledger

### ISSUE THREAD

**Issue by T-Dnzt** [omisego/ewallet#547]
Currently it's possible to query balances of a single wallet, not multiple, at a time. This means that for an account or user that has multiple wallets, it requires N-wallet times in order to fetch all balances that the account/user has.

This could be a performance gain by allowing the balances for multiple wallets to be fetched at a time.

**Comment by unnawut** [comment]
Instead of accepting a single wallet/wallet address and returning the balances directly, these modules need to be added to accept multiple wallet addresses and return a map of %{wallet_address => balances}` for the given wallet addresses.

- [ ] `LocalLedgerDB.CachedBalance.get()`
- [ ] `LocalLedger.CachedBalance.all()`
- [ ] `LocalLedger.Wallet.all_balances()`
- [ ] `EWallet.BalanceFetcher.all()`
