### ISSUE TITLE
Create a mix task to update the settings values based on current ENV variables

### ISSUE THREAD

**Issue by T-Dnzt** [omisego/ewallet#554]

**Comment by unnawut** [comment]
... and maybe shows warning during the server start up if it detects that obsoleted ENV variables still exists

**Comment by unnawut** [comment]
1. Build a list of environment variables to check for, mapped to the fields in the database
2. Do value sanitization/conversion required by the DB settings
3. Confirm the env vars migration plan with the user, then saves to database after confirmation
4. Since env vars need to be removed manually by the user, shows warning during the application start up if the env values still exists but not used

**Comment by T-Dnzt** [comment]
@unnawut looks good, for `3.` let's make it optional tho. If `-y` is passed, then it doesn't require confirmation.
