### ISSUE TITLE
Improve email validation regex

### ISSUE THREAD

**Issue by jpopxfile** [omisego/ewallet#587]
# Subject of the issue

The email validation regex may allow some invalid emails to be validated as valid.

# Your environment

https://github.com/omisego/ewallet/blob/master/apps/ewallet/lib/ewallet/web/email_validator.ex#L5

# Steps to reproduce

```
defmodule EmailValidator do
  @moduledoc """
  This module validates an email string.
  """
  @email_regex ~r/^[^\@]+\@[^\@]+$/

  @doc """
  Checks whether the email address looks correct.
  """
  @spec valid?(String.t() | nil) :: boolean()
  def valid?(nil), do: false

  def valid?(email) do
    Regex.match?(@email_regex, email)
  end

  @doc """
  Checks whether the email address looks correct.
  Returns `{:ok, email}` if valid, returns `{:error, :invalid_email}` if invalid.
  """
  @spec validate(String.t() | nil) :: {:ok, String.t()} | {:error, :invalid_email}
  def validate(nil), do: {:error, :invalid_email}

  def validate(email) do
    if Regex.match?(@email_regex, email) do
      {:ok, email}
    else
      {:error, :invalid_email}
    end
  end
end

IO.puts Kernel.inspect(EmailValidator.validate("aaa@example"))
IO.puts Kernel.inspect(EmailValidator.validate("aaa@example..com"))
```

# Expected behavior
These 2 test cases should not be valid emails

# Actual behavior
They are validated as valid.

```
$elixir main.exs
{:ok, "aaa@example"}
{:ok, "aaa@example..com"}
```

# Suggested Mitigation
How about a regex pattern like this?
`^[\w.+-]+\@(([\w-]+)[.]+)+[a-zA-Z]{2,}$`

Will have to write test cases using various invalid email address formats, but I think the coverage of this would be better.

Let me know what you think.

**Comment by T-Dnzt** [comment]
Email regex are never perfect, which is why we decided to use a simple one. This regex only acts as a simple filter, the actual check happens when the confirmation email is sent. If we were to go with a more advanced regex, we'd probably pick one compliant with the [RFC 5322](https://www.ietf.org/rfc/rfc5322.txt) like:

```
(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
```

Now the question is do we want to go there? This regex is supposed to work with 99.99% of the emails so I don't mind using it. Until now, we decided not to care about format and rely heavily on the confirmation, but now that you're bringing it up, it might be the right time to change it.

But let's keep in mind that, one day, someone from the 0.01% won't be able to use his/her email and we'll need to do something. When this happens, telling someone the email they want to use is invalid is not good enough, you need to tell them why, and potentially offer suggestions on how to fix it. We can worry about that later tho 😅

**Comment by jpopxfile** [comment]
Makes sense. Let's close this then, since you guys have thought over this already when choosing the simple regex.
