### ISSUE TITLE
Link to API error codes

### ISSUE THREAD

**Issue by kartsims** [omisego/ewallet#92]
# Subject of the issue

The list of API error codes is on Google Drive and seems to be access-protected.

# Steps to reproduce

Access the "eWallet Error Codes" link from this page (in incognito mode for instance)
https://ewallet.demo.omisego.io/api/swagger#/

# Expected behavior

See the doc

# Actual behavior

Authorization prompt from Google Drive

**Comment by T-Dnzt** [comment]
Thank you (and congratz) for opening the first issue ever! We totally forgot to update that link (the Google Sheet is not actually up-to-date). We'll work on figuring out the best way to share those (a big overhaul of the internal error handling is coming soon, which might affect the way we share them).

In the meantime, the easiest way to see all the potential errors is to check the `ErrorHandler` modules:

- [Admin API](https://github.com/omisego/ewallet/blob/develop/apps/admin_api/lib/admin_api/v1/error_handler.ex)
- [eWallet API](https://github.com/omisego/ewallet/blob/develop/apps/ewallet_api/lib/ewallet_api/v1/error_handler.ex)

**Comment by unnawut** [comment]
Throwing an idea...

Since now we have [EWallet.Web.APIDocs](https://github.com/omisego/ewallet/blob/develop/apps/ewallet/lib/ewallet/web/api_docs.ex). We could expose `@errors` from [`AdminAPI.V1.ErrorHandler`](https://github.com/omisego/ewallet/blob/develop/apps/admin_api/lib/admin_api/v1/error_handler.ex) and [`EWalletAPI.V1.ErrorHandler`](https://github.com/omisego/ewallet/blob/develop/apps/ewallet_api/lib/ewallet_api/v1/error_handler.ex) and display them in json format, etc. This way we don't need to maintain code & docs separately.

Maybe serve them under URLs like `/admin/api/docs/error-codes` or `/admin/api/docs/error-codes.json`, which should work well with the new [EWallet.Web.APIDocs](https://github.com/omisego/ewallet/blob/develop/apps/ewallet/lib/ewallet/web/api_docs.ex).

**Comment by T-Dnzt** [comment]
@unnawut Good idea! Let's do that. Since this issue was specifically about the broken link in the docs, we're gonna close it. We'll be working on integrating the errors list.

**Comment by unnawut** [comment]
Note that we've just merged the PR that provides error code listings: #140. Thanks for reporting @kartsims  :tada:
